# Generated by Django 3.0.5 on 2020-11-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='release_data',
            field=models.DateTimeField(),
        ),
    ]
