# Generated by Django 3.0.5 on 2020-11-12 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201112_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='release_data',
            new_name='release_date',
        ),
    ]
